// Generated by Wrangler by running `wrangler types`

interface Env {
	MATCHMAKER: DurableObjectNamespace<import("./src/index").MatchMaker>;
	MATCH: DurableObjectNamespace<import("./src/index").Match>;
}
